const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{golge: 0},
	{arkaplan: 0},
	{spbeyaz: 0},
	{mebLogo: 0},
	{emegigecenler: 0},
	{about: 0},
	{reference: 0},
	{Logo: 0},
	{logoYazi: 0},
	{harf: 0},
	{Flash: 0},
	{kontrol: 0},
	{Sine: 0},
	{baloncuklar: 0},
	{BalonUfleyenCocuk: 0},
	{harfNo: 0},
	{harfCizgi: 0},
	{kelimeGorseller: 0},
	{harfDairesi: 0},
	{kelimeGecis: 0},
	{skor: 0},
	{scoreRes: 0},
	{tebrikler: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{AJAX: 0},
	{kelimeler: 0},
	{kelimeSirasi: 0},
	{btn_basla: 0},
	{btn_anasayfa: 0},
	{btn_emegigecenler: 0},
	{btn_kaynakca: 0},
	{btn_replay: 0},
	{durum: 0},
	{btn_ses: 0},
	{btn_tamekran: 0},
	{btn_Bilgi: 0},
	{btn_next: 0},
	{Pin: 0},
	{balonHarf: 0},
	{balonHarfAltta: 0},
	{text_Skor: 0},
	{ButonAilesi: 0},
	{AnaSayfaGorseller: 0},
	{rastgeleHarflerKelime: 0},
	{harfSayisi: 0},
	{tiklanabilir: 0},
	{secilenKelime: 0},
	{kelime: 0},
	{musicDurum: 0}
];

self.InstanceType = {
	golge: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	spbeyaz: class extends self.ISpriteInstance {},
	mebLogo: class extends self.ISpriteInstance {},
	emegigecenler: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	reference: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	logoYazi: class extends self.ISpriteInstance {},
	kontrol: class extends self.ISpriteInstance {},
	baloncuklar: class extends self.ISpriteInstance {},
	BalonUfleyenCocuk: class extends self.ISpriteInstance {},
	harfCizgi: class extends self.ISpriteInstance {},
	kelimeGorseller: class extends self.ISpriteInstance {},
	harfDairesi: class extends self.ISpriteInstance {},
	kelimeGecis: class extends self.ISpriteInstance {},
	skor: class extends self.ISpriteInstance {},
	scoreRes: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	kelimeler: class extends self.IArrayInstance {},
	kelimeSirasi: class extends self.IArrayInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	btn_emegigecenler: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_replay: class extends self.ISpriteInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	btn_tamekran: class extends self.ISpriteInstance {},
	btn_Bilgi: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	balonHarf: class extends self.ITextInstance {},
	balonHarfAltta: class extends self.ITextInstance {},
	text_Skor: class extends self.ITextInstance {},
	ButonAilesi: class extends self.ISpriteInstance {},
	AnaSayfaGorseller: class extends self.ISpriteInstance {}
}